For an unknown reason that I couldn't figure out, I was getting a '/anaconda/lib/python3.6/site-packages/hmmlearn/base.py:459: RuntimeWarning: divide by zero encountered in log
  np.log(self.startprob_)' error when running code using hmmlearn inside Jupyter. 
I did not encounter this error when running the code in Terminal within the AIND Anaconda environment. Regardless of the errors spamming the output logs, the code did pass all tests and seemed to work fine (you just need to scroll to the very bottom of the output logs in some cases).